// benchmark/solidstart-counter/src/routes/index.tsx
import { createSignal } from "solid-js";

export default function Home() {
  const [count, setCount] = createSignal(0);

  return (
    <main>
      <h1>SolidStart Counter</h1>
      <p>Current count: {count()}</p>
      <button type="button" onClick={() => setCount((c) => c + 1)}>
        +
      </button>
    </main>
  );
}

// benchmark/qwik-counter/src/routes/index.tsx
import { component$, useSignal } from "@builder.io/qwik";
import type { DocumentHead } from "@builder.io/qwik-city";

export default component$(() => {
  const count = useSignal(0);

  return (
    <main>
      <h1>Qwik Counter</h1>
      <p>Current count: {count.value}</p>
      <button type="button" onClick$={() => count.value++}>
        +
      </button>
    </main>
  );
});

export const head: DocumentHead = {
  title: "Qwik Counter",
};
